<pgm> ::= <exp>*
<fun> ::= "[" <exp>* "]"
<exp> ::= <act> | <num> | <wsp>
<act> ::= <var> | <sym> | <fun>
<num> ::= E <real> | <wsp> <real> | <act> <real>
<real> ::= ("0" |  [1-9] [0-9]*) ("." [0-9]+ )?
<wsp> ::= " " | "\t" | "\n" | "\r" "\n"
<var> ::= [a-z]
<sym> ::= <msym> | <bsym> | <ssym> | <vsym> | <fsym> | <esym>
<msym> ::= "+" | "-" | "*" | "/" | "^" | "_"
<bsym> ::= ">" | "=" | "&" | "|" | "~"
<ssym> ::= "%" | "\\" | "$" | "`" | "@"
<vsym> ::= ":" | ";"
<fsym> ::= "!" | "?" | "#" | "<"
<esym> ::= "." | "," | "\""
